export const COMPLETE = 'COMPLETE';
export const INCOMPLETE = 'INCOMPLETE';
export const GetALLCARD = 'GETALLCARD';
export const GETALLCARDSIZES = 'GETALLFILTERSIZE';
export const ADDCRITERIA = 'ADDCRITERIA';